### ISSUE TITLE
problem installing v1.2

### ISSUE THREAD

**Issue by zktuong** [dpeerlab/Palantir#102]
Hi, thanks for this really great package -

I'm running into issues with installing the latest version (1.2) on pypi and was wondering if this has come up as an issue for you guys?

https://github.com/zktuong/dandelion/actions/runs/4463726559/jobs/7839217839#step:17:85

reverting to 1.0.1 works

**Comment by zktuong** [comment]
hi i just tried the following manually:

### ensured i was starting fresh
```shell
conda clean --all
pip cache purge
```

### create a new environment
```shell
conda create --name test "python=3.10"
conda activate test
```

### install palantir
```shell
pip install palantir
```

And this is what happened:
```bash
(test)jovyan@jupyter-zktuong:~$ pip install palantir
Collecting palantir
  Downloading palantir-1.2-py3-none-any.whl (27 kB)
Collecting numpy>=1.14.2
  Downloading numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 35.9 MB/s eta 0:00:00
Collecting scikit-learn
  Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 46.5 MB/s eta 0:00:00
Collecting tables>=3.4.2
  Downloading tables-3.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 44.7 MB/s eta 0:00:00
Collecting seaborn>=0.8.1
  Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 8.1 MB/s eta 0:00:00
Collecting scanpy>=1.6.0
  Downloading scanpy-1.9.3-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 22.8 MB/s eta 0:00:00
Collecting pygam
  Downloading pygam-0.9.0-py3-none-any.whl (522 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 522.2/522.2 kB 14.5 MB/s eta 0:00:00
Collecting joblib
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 9.7 MB/s eta 0:00:00
Collecting pandas>=0.22.0
  Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 44.1 MB/s eta 0:00:00
Collecting scipy>=1.3
  Downloading scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 25.4 MB/s eta 0:00:00
Collecting tzlocal
  Downloading tzlocal-4.3-py3-none-any.whl (20 kB)
Collecting cmake
  Downloading cmake-3.26.0-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 34.1 MB/s eta 0:00:00
Collecting fcsparser>=0.1.2
  Downloading fcsparser-0.2.4-py3-none-any.whl (5.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 10.5 MB/s eta 0:00:00
Collecting PhenoGraph>=1.5.3
  Downloading PhenoGraph-1.5.7-py3-none-any.whl (159 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.6/159.6 kB 7.2 MB/s eta 0:00:00
Collecting networkx>=2.1
  Downloading networkx-3.0-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 27.5 MB/s eta 0:00:00
Collecting Cython
  Downloading Cython-0.29.33-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 17.5 MB/s eta 0:00:00
Collecting matplotlib>=2.2.2
  Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 50.9 MB/s eta 0:00:00
Requirement already satisfied: six in ./my-conda-envs/test/lib/python3.10/site-packages (from fcsparser>=0.1.2->palantir) (1.16.0)
Requirement already satisfied: setuptools in ./my-conda-envs/test/lib/python3.10/site-packages (from fcsparser>=0.1.2->palantir) (67.6.0)
Collecting pillow>=6.2.0
  Downloading Pillow-9.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 33.9 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: python-dateutil>=2.7 in ./my-conda-envs/test/lib/python3.10/site-packages (from matplotlib>=2.2.2->palantir) (2.8.2)
Requirement already satisfied: packaging>=20.0 in ./my-conda-envs/test/lib/python3.10/site-packages (from matplotlib>=2.2.2->palantir) (23.0)
Collecting pyparsing>=2.3.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 4.9 MB/s eta 0:00:00
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 26.4 MB/s eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 kB 12.2 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.39.2-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 23.3 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 kB 12.0 MB/s eta 0:00:00
Collecting leidenalg>=0.8.2
  Downloading leidenalg-0.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 21.3 MB/s eta 0:00:00
Requirement already satisfied: psutil>4 in ./my-conda-envs/test/lib/python3.10/site-packages (from PhenoGraph>=1.5.3->palantir) (5.9.4)
Collecting patsy
  Downloading patsy-0.5.3-py2.py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.8/233.8 kB 5.5 MB/s eta 0:00:00
Collecting anndata>=0.7.4
  Downloading anndata-0.8.0-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.1/96.1 kB 4.4 MB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 3.7 MB/s eta 0:00:00
Collecting natsort
  Downloading natsort-8.3.1-py3-none-any.whl (38 kB)
Collecting session-info
  Downloading session_info-1.0.0.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting h5py>=3
  Downloading h5py-3.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 28.9 MB/s eta 0:00:00
Collecting numba>=0.41.0
  Downloading numba-0.56.4-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 31.9 MB/s eta 0:00:00
Collecting umap-learn>=0.3.10
  Downloading umap-learn-0.5.3.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 kB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting statsmodels>=0.10.0rc2
  Downloading statsmodels-0.13.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 15.4 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting numexpr>=2.6.2
  Downloading numexpr-2.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (381 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.4/381.4 kB 2.6 MB/s eta 0:00:00
Collecting py-cpuinfo
  Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Collecting blosc2~=2.0.0
  Downloading blosc2-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 40.8 MB/s eta 0:00:00
Collecting progressbar2<5.0.0,>=4.2.0
  Downloading progressbar2-4.2.0-py2.py3-none-any.whl (27 kB)
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting msgpack
  Downloading msgpack-1.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (316 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.8/316.8 kB 8.4 MB/s eta 0:00:00
Collecting igraph<0.11,>=0.10.0
  Downloading igraph-0.10.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 34.2 MB/s eta 0:00:00
Collecting llvmlite<0.40,>=0.39.0dev0
  Downloading llvmlite-0.39.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.6/34.6 MB 12.4 MB/s eta 0:00:00
Collecting numba>=0.41.0
  Downloading numba-0.56.3-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 35.3 MB/s eta 0:00:00
  Downloading numba-0.56.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 31.6 MB/s eta 0:00:00
  Downloading numba-0.56.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 23.7 MB/s eta 0:00:00
  Downloading numba-0.55.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 28.0 MB/s eta 0:00:00
  Downloading numba-0.55.1-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 20.8 MB/s eta 0:00:00
Collecting llvmlite<0.39,>=0.38.0rc1
  Downloading llvmlite-0.38.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 12.9 MB/s eta 0:00:00
Collecting numba>=0.41.0
  Downloading numba-0.55.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 37.9 MB/s eta 0:00:00
  Downloading numba-0.51.2.tar.gz (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting llvmlite<0.35,>=0.34.0.dev0
  Downloading llvmlite-0.34.0.tar.gz (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting python-utils>=3.0.0
  Downloading python_utils-3.5.2-py2.py3-none-any.whl (24 kB)
Collecting pynndescent>=0.5
  Downloading pynndescent-0.5.8.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 24.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting tzdata
  Downloading tzdata-2022.7-py2.py3-none-any.whl (340 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 340.1/340.1 kB 22.4 MB/s eta 0:00:00
Collecting stdlib_list
  Downloading stdlib_list-0.8.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 7.5 MB/s eta 0:00:00
Collecting texttable>=1.6.2
  Downloading texttable-1.6.7-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: numba, umap-learn, session-info, llvmlite, pynndescent
  Building wheel for numba (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6zouwcen/numba_3294b22b9dac4af6be0413468fd97588/setup.py", line 354, in <module>
          metadata['ext_modules'] = get_ext_modules()
        File "/tmp/pip-install-6zouwcen/numba_3294b22b9dac4af6be0413468fd97588/setup.py", line 87, in get_ext_modules
          import numpy.distutils.misc_util as np_misc
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6zouwcen/numba_3294b22b9dac4af6be0413468fd97588/setup.py", line 354, in <module>
          metadata['ext_modules'] = get_ext_modules()
        File "/tmp/pip-install-6zouwcen/numba_3294b22b9dac4af6be0413468fd97588/setup.py", line 87, in get_ext_modules
          import numpy.distutils.misc_util as np_misc
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for numba
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.3-py3-none-any.whl size=82816 sha256=62b4ae7f1943097d7214539513a762123870baff3fc725ca88ea1f7d1876a18a
  Stored in directory: /home/jovyan/.cache/pip/wheels/a0/e8/c6/a37ea663620bd5200ea1ba0907ab3c217042c1d035ef606acc
  Building wheel for session-info (setup.py) ... done
  Created wheel for session-info: filename=session_info-1.0.0-py3-none-any.whl size=8026 sha256=5c0cfd7c28189d3d3fe972a9b8520cad99266551228d918437d6eee2fa4688c0
  Stored in directory: /home/jovyan/.cache/pip/wheels/6a/aa/b9/eb5d4031476ec10802795b97ccf937b9bd998d68a9b268765a
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      /home/jovyan/my-conda-envs/test/bin/python3.1 /tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/home/jovyan/my-conda-envs/test/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/jovyan/my-conda-envs/test/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/jovyan/my-conda-envs/test/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/jovyan/my-conda-envs/test/lib/python3.10/subprocess.py", line 1847, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py", line 191, in <module>
          main()
        File "/tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py", line 181, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/home/jovyan/my-conda-envs/test/bin/python3.1' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
  Building wheel for pynndescent (setup.py) ... done
  Created wheel for pynndescent: filename=pynndescent-0.5.8-py3-none-any.whl size=55496 sha256=8a7e15d00e0f3953b38f35e4f71b0245d7776f1ec542eb47d360634e3408c2e8
  Stored in directory: /home/jovyan/.cache/pip/wheels/f8/5c/b4/a06301605095861524c1c7268a0d445b3a4c50292ce3bec24c
Successfully built umap-learn session-info pynndescent
Failed to build numba llvmlite
Installing collected packages: texttable, stdlib_list, pytz, py-cpuinfo, msgpack, cmake, tzdata, tqdm, threadpoolctl, session-info, python-utils, pyparsing, pillow, numpy, networkx, natsort, llvmlite, kiwisolver, joblib, igraph, fonttools, Cython, cycler, blosc2, scipy, pytz-deprecation-shim, progressbar2, patsy, pandas, numexpr, numba, leidenalg, h5py, contourpy, tzlocal, tables, statsmodels, scikit-learn, pygam, matplotlib, fcsparser, anndata, seaborn, pynndescent, PhenoGraph, umap-learn, scanpy, palantir
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running install
      /home/jovyan/my-conda-envs/test/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      got version from file /tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
      running build_ext
      /home/jovyan/my-conda-envs/test/bin/python3.1 /tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/home/jovyan/my-conda-envs/test/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/jovyan/my-conda-envs/test/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/jovyan/my-conda-envs/test/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/jovyan/my-conda-envs/test/lib/python3.10/subprocess.py", line 1847, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py", line 191, in <module>
          main()
        File "/tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py", line 181, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-6zouwcen/llvmlite_b86444259f7a45ebb3f94dd26342045d/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/home/jovyan/my-conda-envs/test/bin/python3.1' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by zktuong** [comment]
some update - i think the reason is the numba conflict caused in the numpy version required by `pygam`:

```bash
(test)jovyan@jupyter-zktuong:~$ pip install "pygam"
Requirement already satisfied: pygam in ./my-conda-envs/test/lib/python3.10/site-packages (0.9.0)
Requirement already satisfied: progressbar2<5.0.0,>=4.2.0 in ./my-conda-envs/test/lib/python3.10/site-packages (from pygam) (4.2.0)
Collecting numpy<2.0.0,>=1.24.2
  Using cached numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Requirement already satisfied: scipy<2.0.0,>=1.10.1 in ./my-conda-envs/test/lib/python3.10/site-packages (from pygam) (1.10.1)
Requirement already satisfied: python-utils>=3.0.0 in ./my-conda-envs/test/lib/python3.10/site-packages (from progressbar2<5.0.0,>=4.2.0->pygam) (3.5.2)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.
```

**Comment by ktpolanski** [comment]
It seems that the new pygam releases are very recent, even newer than palantir 1.2. I was able to get the newest palantir installed by doing `pip install pygam==0.8.0` ahead of `pip install palantir`.

**Comment by ManuSetty** [comment]
Thank you! We will force the use of `pygam==0.8.0` in a patch.

**Comment by rahulnutron** [comment]
> It seems that the new pygam releases are very recent, even newer than palantir 1.2. I was able to get the newest palantir installed by doing `pip install pygam==0.8.0` ahead of `pip install palantir`.

This solution worked for me. Thanks!
