### ISSUE TITLE
error while reading mtx file

### ISSUE THREAD

**Issue by Sumithrasank** [dpeerlab/Palantir#30]
Hi, Thanks for developing Palantir. I have been trying to read in a count matrix in mtx format along with the gene_file_name via palantir.io.from_mtx but get an error which I don't understand. Can you help me out with this?

>>> counts = palantir.io.from_mtx('matrix.mtx',gene_name_file='genes.tsv')
Traceback (most recent call last):
  File "/Users/sumithrasankararaman/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1654, in create_block_manager_from_blocks
    make_block(values=blocks[0], placement=slice(0, len(axes[0])))
  File "/Users/sumithrasankararaman/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 3041, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/Users/sumithrasankararaman/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 125, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 3128, placement implies 26541

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sumithrasankararaman/opt/anaconda3/lib/python3.7/site-packages/palantir/io.py", line 32, in from_mtx
    df = pd.DataFrame(count_matrix.todense(), columns=gene_names)
  File "/Users/sumithrasankararaman/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 464, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/Users/sumithrasankararaman/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 210, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/Users/sumithrasankararaman/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1664, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/Users/sumithrasankararaman/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1694, in construction_error
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (26541, 3128), indices imply (26541, 26541)

Thank You

**Comment by awnimo** [comment]
Thank you for using our tool!
It is possible that `genes.tsv` has dimensions not matching the matrix.
Can you run this snippet and report back the output please?
```
import numpy as np
gene_names = np.loadtxt("genes.tsv", dtype="S")
gene_names = np.array([gene.decode("utf-8") for gene in gene_names])
gene_names.shape
```
The output is expected to be `(3128,)` for a correct column index for your matrix, assuming the matrix is a cell `x` gene matrix.
